name: CMake build and test

on:
  pull_request:
    paths:
      - CMakeLists.txt
      - src/**/CMakeLists.txt
      - src/**/*.c
      - src/**/*.h
      - tests/**/CMakeLists.txt
      - tests/**/*.c*
      - tests/**/*.h*

jobs:
  cmake_build_and_test:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - run: sudo apt update && sudo apt install ninja-build libgtest-dev python3.12-venv llvm-18-tools
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - run: cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=Debug
      - run: cmake --build build
      - run: cmake --build build --target test
      - run: python3 -m venv .venv && source .venv/bin/activate && pip install lit && cmake --build build --target lit-test
